services:
  - type: web
    name: gift-tracker-api
    env: node
    plan: free
    buildCommand: |
      cd server
      npm install --production
      npm list express
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false 