-- Disable RLS on existing tables
ALTER TABLE people DISABLE ROW LEVEL SECURITY;
ALTER TABLE occasions DISABLE ROW LEVEL SECURITY;
ALTER TABLE gifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE budgets DISABLE ROW LEVEL SECURITY; 